### ISSUE TITLE
Pages stop loading after a few

### ISSUE THREAD

**Issue by sagestrike08** [friendlyanon/GelbooruEnhancement#7] opened 2018-01-10 08:49 UTC
Sorry to be a bother, I have no idea whats going on. I find that after 5 or so pages the script seems to stop. I'm in Chrome with Tampermonkey.

**Comment by friendlyanon** [comment] 2018-01-10 23:08
Insufficient amount of details. What page is this happening on, what other addons are you using, chrome version, TM version, any error messages in console, is you internet connection stable enough, etc.

**Comment by sagestrike08** [comment] 2018-01-11 04:14
Nothing else is running in Tampermonkey.
Chrome is Version 63.0.3239.132 (Official Build) (64-bit)
Tampermonkey is 4.5.5660
Not sure how to see error messages in console.
No internet issues.

The issues I'm having apply to any time there is another page that could be loaded in a row. Such as most recent posts or browsing a specific tag.

First time I go to the website in a day(ish) it'll stop loading pages after 2 or so. I think it does this because it's trying to force a new window pop-up that would normally happen at that time when browsing page by page.  

After using the site a bit more trying to troubleshoot my issues to better explain thing in this thread I've noticed more specific behavior. When first loading any page the script isn't loading future pages (not an issue), and once I scroll down it then attempts to load future pages. If I scroll down and browse while they load it stops, generally that means 4 or 5 future pages will load before stopping. If I get them to start preloading and then wait on the first page I can see it grabbing more and more pages endlessly as my scroll bar get's smaller and smaller, but then I can't scroll down and continue to browse or it will stop loading future pages. If I scroll back to the top it will grab future pages again.

I'm pretty sure it's only loading future pages when this is on screen. https://imgur.com/teEGtjD

I don't think Gelbooru has an issue, but some sites also will cut service if you're loading too many images too quickly. So this isn't vital, but one suggestion I have would be for it to grab 2 or 3 pages beyond the one your viewing rather than loading them infinitely. Just a small suggestion.

**Comment by friendlyanon** [comment] 2018-01-12 18:42
I can't really reproduce this behaviour in any way.
You can open your browser console with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>, the endless scroll script should retry 10 times before giving up and spitting out the cause of the error.

**Comment by sagestrike08** [comment] 2018-01-13 07:52
This is what is shown on the console tab. https://i.imgur.com/6dtYpPI.jpg

**Comment by friendlyanon** [comment] 2018-10-20 10:05
Closing this for now, since no conclusive info was shared that would suggest Endless Scroll is not working.

**Closed as completed by friendlyanon** 2018-10-20 10:05 UTC
